// Generated by scripts/build-sop-runtime.mjs. Do not edit by hand.
export const SOP_RUNTIME_PACKAGE = {
  "runtime_schema": "sop-runtime.v1",
  "library_id": "workplace_newcomer_year_one",
  "source_schema_version": "sop.v2.2",
  "source_version": "2.3.0-reviewed",
  "source_sha256": "e1eff458f317929c0d2d0a7c364893c92c722b4abc57556b8eb238adb7bf1d1d",
  "taxonomy_sha256": "7afb3f29c46be00883a65ed23ddebaadcb5b548ad1809a9271ba20c8e2b47610",
  "release_status": "BLOCKED_NO_ACTIVE_MODULES",
  "source_updated_at": "2026-07-19",
  "module_count": 0,
  "selection_rules": {
    "max_modules_per_retrieval": 3,
    "requires_user_confirmation": true,
    "allow_no_match": true
  },
  "modules": []
};
